/*
This file was autogenerated from 02_fully_connected.ipynb
        
If you edit it, be sure that:
  1. there is no diff between this file and the corresponding notebook prior to editing
  2. you don't touch the comments looking like // cell ## as it would break the way back to the notebook
        
Run *** when you are done to update the notebooks with your change.
*/
        
//cell2
import Path
import TensorFlow

//cell6
public typealias TF=Tensor<Float>

//cell8
public func normalize(_ x:TF, mean:TF, std:TF) -> TF {
    return (x-mean)/std
}

//cell14
public func testNearZero(_ a: TF, tolerance: Float = 1e-3) {
    assert((abs(a) .< tolerance).all(), "Near zero: \(a)")
}

public func testSame(_ a: TF, _ b: TF) {
    // Check shapes match so broadcasting doesn't hide shape errors.
    assert(a.shape == b.shape)
    testNearZero(a-b)
}

//cell39
public func mse(_ out: TF, _ targ: TF) -> TF {
    return (out.squeezingShape(at: -1) - targ).squared().mean()
}
